### ISSUE TITLE
Support for MS SQL

### ISSUE THREAD

**Issue by gwque** [nim-lang/db_connector#20]
Attempting to connect to MS SQL using a connection string (necessary to specify certain connection options beyond the standard). However, when trying that using db_odbc open("Server=myserver;Database=mydb;Driver={ODBC Driver 17 for SQL Server};Trusted_Connection=yes;Encrypt=false", "", "", ""), one gets:

"Error: HY090 [Microsoft][ODBC Driver Manager] Invalid string or buffer length"

**Update**
I've found that db_odbc uses the SQLConnect API method which apparently only takes a DSN or server name along with the user, pwd, and db names for basic, straight-forward connections. From what I've gathered, a call to SQLDriverConnect is needed instead. I've an overload/alternate of open() that resolves that. Now working to incorporate an overload of the instantRows() call that returns column information (DBColumns) like the db_postgres module does.

**Comment by gwque** [comment]
Update: I created a DSN on the windows machine and the connector appears to work connecting to that named instance. However, most often we don't used these types of connections (DSN) and prefer connection strings that will accept all the connection details/parameters. Those single-string parameters might also include user name, password, and database in the one string (rather than using those specialized parameters in the open function. Perhaps the limitation from using such a connection string is a varchar limit in the ODBC connector methods; is it possible to extend to more characters?

**Comment by Araq** [comment]
> If nim is expected to compete with Rust or other new languages, it will have to be able to connect to SQL Server databases.

Lol.
